# Build Stage
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV REACT_APP_API_URL=/api

RUN npm run build

# Serve Stage
FROM node:20-alpine

WORKDIR /app

# ติดตั้ง serve สำหรับรัน static files
RUN npm install -g serve

# ก๊อปปี้ไฟล์ที่ build แล้วมา
COPY --from=build /app/build ./build

EXPOSE 8000

CMD ["serve", "-s", "build", "-l", "8000"]
